name: imb_syn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - imbalanced-learn
  - pip
  - skopt
  - lightgbm
  - pip:
      - sdv  
